// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
let options = {"masterHistoryType":"browser","base":"/","apps":[{"name":"slave","entry":"http://127.0.0.1:5555"},{"name":"slave-app2","entry":"http://127.0.0.1:7002"}]};
export const getMasterOptions = () => options;
export const setMasterOptions = (newOpts) => options = ({ ...options, ...newOpts });
