// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/home","id":"1"},"2":{"path":"/count","id":"2"},"3":{"path":"/nav","id":"3"}},
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__home" */'@/pages/home.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__count" */'@/pages/count.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__nav" */'@/pages/nav.tsx')),
},
  };
}
