// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/","redirect":"/home","id":"1"},"2":{"path":"/home","id":"2"},"3":{"path":"/slave/*","microApp":"slave","id":"3"},"4":{"path":"/animal","id":"4"},"5":{"path":"/animal/ant/*","microApp":"slave-app2","parentId":"4","id":"5"},"6":{"path":"/manual-slave/*","id":"6"}},
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'3': React.lazy(
              () => Promise.resolve((async () => {
          const { getMicroAppRouteComponent } = await import('@@/plugin-qiankun-master/getMicroAppRouteComponent');
          return getMicroAppRouteComponent({ appName: 'slave', base: '/', routePath: '/slave/*', masterHistoryType: 'browser', routeProps: {} })
        })()).then(e => e?.default ? e : ({ default: e }))
            ),
'4': React.lazy(() => import( './EmptyRoute')),
'5': React.lazy(
              () => Promise.resolve((async () => {
          const { getMicroAppRouteComponent } = await import('@@/plugin-qiankun-master/getMicroAppRouteComponent');
          return getMicroAppRouteComponent({ appName: 'slave-app2', base: '/', routePath: '/animal/ant/*', masterHistoryType: 'browser', routeProps: {} })
        })()).then(e => e?.default ? e : ({ default: e }))
            ),
'6': React.lazy(() => import(/* webpackChunkName: "p__manual-slave" */'@/pages/manual-slave.tsx')),
},
  };
}
