// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, Helmet, useAppData, useSelectedRoutes, useClientLoaderData, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/github/test/qiankun-slave/node_modules/.pnpm/@umijs+renderer-react@4.0.44_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react';
export type {  History } from 'D:/github/test/qiankun-slave/node_modules/.pnpm/@umijs+renderer-react@4.0.44_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/github/test/qiankun-slave/node_modules/.pnpm/umi@4.0.44_nvi3gncsqfi5zgpswpx3gcop7m/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
export { Provider, useModel } from 'D:/github/test/qiankun-slave/.umi/plugin-model';
export { connectMaster, MicroAppLink } from 'D:/github/test/qiankun-slave/.umi/plugin-qiankun-slave';
// plugins types.d.ts
export { defineApp } from './core/defineApp'
export type {  RuntimeConfig } from './core/defineApp'
